/** @type {import('tailwindcss').Config} */
import color from "tailwindcss/colors";
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screen: {
      xl: { max: "1536px" },
      "2xl": { min: "1800px", max: "2500px" },
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      backhover: "#E5EDFF",
      primary: "#2563eb",
      primary_hover: "#3b82f6",
      success: "#4cbb17",
      badge_blue: "#93c5fd",
      voilet: "#5B00CC",
      black: "#000000",
      "soft-green": "#53CB89",
      "soft-blue": "#59F2F6",
      "soft-orange": "#FFB600",
      fuchsia: color.blue[600],
      pink: color.pink[700],
      yellow: color.yellow[100],
      "home-gradient-shade": "rgb(0,7,36);",
      heading: "#09162A",
      cyan: color.cyan[100],
      "cyan-50": color.cyan[50],
      background: color.slate[800],
      border: color.slate[400],
      input_color: color.gray[400],
      btn_y_main: color.yellow[300],
      btn_y_hover: color.yellow[500],
      btn_p_main: color.purple[700],
      btn_p_hover: color.purple[800],
      background_color: color.slate[50],
      "slate-light": color.slate[100],
      orange: "#fb923c",
      neon: "#a3e635",
      sky: "#60a5fa",
      "sky-2": "#0369a1",
      bot: "#0057FF",
      "time-bot": "#60a5fa",
      card_bg: "#e4e4e7",
      table_bg: "#f1fbfd",
      custom_text: "#E8E8E8",
      "custom-small": "#8ed1fc",
      "first-section-color": "#7ec1ec",
      "text-dark-color": "#36454F",
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      primary: "#2563eb",
      backhover: "#E5EDFF",
      voilet: "#5B00CC",
      black: "#000000",
      "soft-green": "#53CB89",
      "soft-blue": "#59F2F6",
      "soft-orange": "#FFB600",
      fuchsia: color.blue[600],
      pink: color.pink[700],
      yellow: color.yellow[100],
      "home-gradient-shade": "rgb(0,7,36);",
      heading: "#09162A",
      cyan: color.cyan[100],
      "cyan-50": color.cyan[50],
      background: color.slate[800],
      border: color.slate[400],
      input_color: color.gray[400],
      border_color: "#00000017",
      btn_y_main: color.yellow[300],
      btn_y_hover: color.yellow[500],
      btn_p_main: color.purple[700],
      btn_p_hover: color.purple[800],
      background_color: color.slate[50],
      "slate-light": color.slate[100],
      orange: "#fb923c",
      neon: "#a3e635",
      sky: "#60a5fa",
      "sky-2": "#0369a1",
      bot: "#0057FF",
      "time-bot": "#60a5fa",
      card_bg: "#e4e4e7",
      table_bg: "#f1fbfd",
      sidebar: "rgb(18, 17, 66)",
      linkhover: "rgb(40, 47, 92)",
      headone: "rgb(18, 17, 66)",
      danger: "#dc2626",
      modal: "#fef2f2",
      gray: "#e4e4e7",
      graywhite: "#F3F3F3",
      skyblue: "#d8e4fa",
      red: "#dc2626",
      label: "#59f2f6",
      fade_text: "#000000db",
      sidebarbg:"#151D23",
      sidebarroute:"#1C252B",
      sidebarsubroute:"#232D32"
    },
    extend: {
      gridTemplateColumns: {
        sideBar: "270px auto",
      },
      boxShadow: {
        "3xl": "0 0.125rem 1.5625rem rgb(0 0 0/10%)",
        "card": 'rgba(149, 157, 165, 0.2) 0px 8px 24px',
        "box":"0 4.5px 3.6px rgba(0,0,0,.014), 0 12.5px 10px rgba(0,0,0,.02), 0 30.1px 24.1px rgba(0,0,0,.026), 0 100px 80px rgba(0,0,0,.04)"
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "home-gradient":
          "linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12)",
        "type-section":
          "linear-gradient(to right, rgb(199, 210, 254), rgb(254, 202, 202), rgb(254, 249, 195))",
        "type-above": "linear-gradient(90deg,#09162A,#293445,white  )      ",
        "type-mobile": "linear-gradient(180deg,#09162A,#293445,white  )      ",
        "sidebar-hover": "radial-gradient(400% 240% at -170% 75%, rgb(153, 0, 102) 10%, rgb(255, 82, 51) 50%, rgb(255, 149, 0) 90%) !important",
        "home-above":
          "linear-gradient(340.76deg,#2250f4 40.7%,#230a5c 80.03%)",
      },
      fontSize: {
        h1: "55px",
        h2: "45px",
        h3: "35px",
        h4: "30px",
        h5: "25px",
        h6: "20px",
        para: "16px",
        "small-para": "14px",
      },
      fontFamily: {
        "generalSans-extraLight": ["GeneralSans-Extralight"],
        "generalSans-light": ["GeneralSans-light"],
        "generalSans-regular": ["GeneralSans-Regular"],
        "generalSans-medium": ["GeneralSans-Medium"],
        "generalSans-semibold": ["GeneralSans-Semibold"],
        "generalSans-bold": ["GeneralSans-Bold"],
        "clash-extraLight": ["ClashDisplay-Extralight"],
        "clash-light": ["ClashDisplay-Light"],
        "clash-regular": ["ClashDisplay-Regular"],
        "clash-medium": ["ClashDisplay-Medium"],
        "clash-semibold": ["ClashDisplay-Semibold"],
        "Inter": ["Inter", "sans-serif"],
        "clash-bold": ["ClashDisplay-Bold"],
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        typing: {
          "0%": {
            width: "0%",
            visibility: "hidden",
          },
          "75%": {
            width: "75%",
          },
          "100%": {
            width: "100%",
          },
        },
        thinking: {
          "0%": {
            width: "0%",
            visibility: "hidden",
          },
          "25%": {
            width: "25%",
          },
          "50%": {
            width: "50%",
          },
          "75%": {
            width: "75%",
          },
          "100%": {
            width: "100%",
          },
        },
        wiggle: {
          "0%": { height: "200px", visibility: "hidden", overflow: "hidden" },
          "5%": { height: "300px", visibility: "hidden", overflow: "hidden" },
          "100%": { height: "536px" },
        },
        shake: {
          "10%, 90%": { transform: "translate3d(-1px, 0, 0)" },
          "20%, 80%": { transform: "translate3d(2px, 0, 0)" },
          "30%, 50%, 70%": { transform: "translate3d(-4px, 0, 0)" },
          "40%, 60%": { transform: "translate3d(4px, 0, 0)" },
        },
        blink: {
          "50%": {
            borderColor: "transparent",
          },
          "100%": {
            borderColor: "white",
          },
        },
        bottoggle: {
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        backbottoggle: {
          "100%": {
            transform: "rotate(-360deg)",
          },
        },
        chattile: {
          "0%": { width: "15%" },
          "100%": { width: "75%" },
        },
      },
      animation: {
        thinking: "typing .5s steps(20) infinite alternate, blink .5s infinite",
        shake: "shake 0.82s cubic-bezier(.36,.07,.19,.97) both",
        typing: "typing 3s steps(50)  alternate, blink .5s",
        wiggle: "wiggle .5s ease-in-out",
        bottoggle: "bottoggle 0.7s ease-in-out",
        backbottoggle: "backbottoggle 0.7s ease-in-out",
        chattile: "chattile 1s ease-in",
        fadeIn: "fadeIn .5s ease-in forwards",
      },
    },
  },
  plugins: [],
  safelist: [
    "animate-[fade-in_1s_ease-in-out]",
    "animate-[fade-in-down_1s_ease-in-out]",
  ],
  variants: {
    animation: ["motion-safe"],
  },
};
