import Sidebar from "@/app/components/Dashboard/AuthLayout/Sidebar";

export const metadata = {
  title: 'Tempo',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return <Sidebar>{children}</Sidebar>;
  }