
import Footer from '../components/Layout/Footer'
import Header from '../components/Layout/Header'
export const metadata = {
    title: 'Tempo',
    description: 'Generated by create next app',
}

export default function PageLayout({ children }) {

    return (
        <div className='w-[1400px] m-auto'>
            <Header /> {children}<Footer />
        </div>
    )
}
