
import Footer from '../components/Layout/Footer'
import Header from '../components/Layout/Header'
export const metadata = {
    title: 'Tempo',
    description: 'Generated by create next app',
}

export default function PageLayout({ children }) {

    return (
        <>
            <Header /> {children}<Footer />
        </>
    )
}
